version: '3'
services:
  rssapi:
    image: rssapi:0.1.0
    ports:
      - 8082:8082
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=8082
      - MONGO_PORT=27017
      - MONGO_URL=172.21.0.2
    depends_on:
      - "mongo"
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always